#!/bin/bash
# Program:
#   Create Web Project
# History:
#   2011/11/01    Jace Ju   First release

project_name="$1"
host_name="$2"
template_path="/Users/jaceju/Sites/project/laravel"

## Get name of project
until [ "$project_name" != "" ]
do
	read -p "Please input Project Name: " project_name
done

## Get name of host
until [ "$host_name" != "" ]
do
	read -p "Please input Host Name: " host_name
done

## Exit if project exists
if test -r "./$project_name" ; then
	echo "Project $project_name exists."
	exit 1
fi

# Start creating
echo "Creating structure of project..."

## Create structure of project
cp -r "$template_path" $project_name > /dev/null
cd $project_name
rm -rf .git
git init
cur_path=`pwd`
cd ../
sudo chmod -R 777 "$project_name/storage"

## Add host name to /etc/hosts
sudo perl -pi -e "s/# VHX STOP/127.0.0.1 $host_name\nfe80::1%lo0 $host_name\n# VHX STOP/g" /etc/hosts

## Add new virtual host
vhost_config="
<Directory \"$cur_path/public/\">
Allow From All
AllowOverride All
</Directory>
<VirtualHost *:80>
ServerName \"$host_name\"
DocumentRoot \"$cur_path/public\"
</VirtualHost>"
sudo sh -c "echo \"$vhost_config\" >> /etc/apache2/extra/httpd-vhosts.conf"

sudo apachectl -k restart
