#!/bin/bash
# Program:
#   Create Web Project
# History:
#   2011/11/01    Jace Ju   First release

project_name="$1"

## Get name of project
until [ "$project_name" != "" ]
do
	read -p "Please input Project Name: " project_name
done

## Exit if project exists
if test -r "./$project_name" ; then
	echo "Project $project_name exists."
	exit 1
fi

# Start creating
echo "Creating project..."

## Create structure of project
composer create-project laravel/laravel $project_name --prefer-dist
cd $project_name
git init
cur_path=`pwd`
cd ../
sudo chmod -R 777 "$project_name/app/storage"
