#!/bin/bash
# Program:
#   Create Web Project
# History:
#   2011/11/01    Jace Ju   First release
PATH=~/.bin:/usr/local/sbin:/usr/local/bin;/usr/sbin:/usr/bin:/sbin:/bin
export PATH

## Set variables
repo_path="/Users/jaceju/Documents/Repositories"
project_name="$1"
temp_path="__template__.$RANDOM.$RANDOM.$RANDOM.$$"
svn_local_url="file://$repo_path"
svn_http_url="http://it-dev.ithome.com.tw/repos"
template_path="/Users/jaceju/Sites/projects/template"
user="_www"
group="_www"
ithome_lib="http://it-dev.ithome.com.tw/repos/ithome_lib/branches/0.2/Ithome"
smarty_lib="http://it-dev.ithome.com.tw/repos/ithome_lib/branches/0.2/Smarty"
zf_lib="http://framework.zend.com/svn/framework/standard/tags/release-1.11.10/library/Zend"

## Get name of project
until [ "$project_name" != "" ]
do
	read -p "Please input Project Name: " project_name
done

## Exit if project exists
if test -r "$repo_path/$project_name" ; then
	echo "Project $project_name exists."
	exit 1
fi

## Create repository
echo "Creating repository..."
cd $repo_path
svnadmin create $project_name > /dev/null

## Create structure of project
echo "Creating structure of project..."
cd $TMPDIR
mkdir $temp_path > /dev/null
cd $temp_path
cp -R "$template_path/" $project_name > /dev/null

## Import project
echo "Importing project..."
svn import $project_name "$svn_local_url/$project_name" -m "Initialize structure of project." > /dev/null

# Checkout project
rm -rf $project_name
svn checkout "$svn_local_url/$project_name/trunk" $project_name > /dev/null

# Set externals
svn propset svn:externals "$ithome_lib Ithome" "$project_name/library" > /dev/null
svn propset svn:externals "$smarty_lib Smarty3" "$project_name/library" > /dev/null
svn propset svn:externals "$zf_lib Zend" "$project_name/library" > /dev/null
svn propset svn:ignore "*" "$project_name/application/temp/compiled" > /dev/null
svn commit $project_name -m "Set properties" > /dev/null

# Changing permission
echo "Changing permissions of repository..."
sudo chown -R "$user" "$repo_path/$project_name" > /dev/null
sudo chgrp -R "$group" "$repo_path/$project_name" > /dev/null

## Clear off temp file
echo "Clearing off temp file..."
cd $TMPDIR
rm -rf $temp_path > /dev/null

echo "done."
echo "The final svn url is '$svn_http_url/$project_name/trunk'"

exit 0
