#!/usr/bin/env bash

################
# Format
################
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
NOCOLOR="\033[0m"
NL="\n"
SP='  '

################
# Get Branches
################
BRANCHES=( $(git branch --merged| egrep -v "(^\*|master|staging|testing)") )

## Run
for i in ${!BRANCHES[@]};do
    git branch -D ${BRANCHES[i]}
done

echo -e "${GREEN}Done${NOCOLOR}"