#!/bin/sh
# must be run as root
case x$1 in
x4) vm=1.4.2;;
x5) vm=1.5.0;;
*) echo "usage:"
echo " sudo switch 4 - select 1.4.2 as default jvm"
echo " sudo switch 5 - select 1.5.0 as default jvm"
exit 1;;
esac
echo Switching to JVM $vm

cd /System/Library/Frameworks/JavaVM.framework/Versions
rm CurrentJDK
ln -s $vm CurrentJDK

java -version
