#!/bin/bash

INPUT_FILE=${1-}

if [ "${INPUT_FILE}" = "" ]
then
  echo "No input file."
  exit 1
fi

OUTPUT_NAME=$(basename "$INPUT_FILE" .md)
pandoc -f markdown -t mediawiki -o "${OUTPUT_NAME}.wiki" "${INPUT_FILE}"