#!/bin/bash
brew install automake autoconf curl pcre re2c mhash libtool icu4c gettext jpeg libxml2 mcrypt gmp libevent
curl -O https://raw.github.com/c9s/phpbrew/master/phpbrew
chmod +x phpbrew
sudo cp phpbrew /usr/local/bin/phpbrew

phpbrew init
phpbrew update

versions=("5.6.24" "7.0.9")
for version in ${versions[@]}; do
  pb-ins $version
done