#!/bin/bash

WORKPATH=`pwd`
JAR="${WORKPATH}/selenium-server-standalone-2.45.0.jar"
FIREFOX="/Applications/Firefox.app/Contents/MacOS/firefox"
LOGFILE="${WORKPATH}/selenium-server.log"
PROFILE="${WORKPATH}/profile"
TIMEOUT=180000

BIN=`which java`
NAME="Selenium Server"
ARGS="-jar ${JAR} -firefoxProfileTemplate ${PROFILE} -timeout ${TIMEOUT} -trustAllSSLCertificates -log ${LOGFILE}"
PIDFILE="/tmp/selenium-server.pid"

case "$1" in
  init)
    echo "Initialing..."
    if [ ! -f ${JAR} ]; then
      wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
    fi
    if [ ! -d ${PROFILE} ]; then
      ${FIREFOX} -CreateProfile "testing ${PROFILE}"
    fi
    echo "Done"
    ;;
  start)
    echo -ne "Starting ${NAME}: "
    ${BIN} -jar ${JAR} -firefoxProfileTemplate ${PROFILE} -timeout ${TIMEOUT} -trustAllSSLCertificates -log ${LOGFILE} &
    echo $! > ${PIDFILE}
    echo " ....OK"
    ;;
  stop)
    echo -ne "Stopping ${NAME}: "
    PID=`cat ${PIDFILE}`
    kill $PID
    rm -f $PIDFILE
    echo " ....OK"
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  *)
    echo "Usage: ${0} {start|stop|restart}"
    exit 1
esac

exit 0


# For Test
# java -jar /vagrant/assets/selenium-server-standalone-2.45.0.jar \
# -firefoxProfileTemplate /vagrant/assets/firefox-profile \
# -htmlSuite *firefox http://www.google.com.com \
# "/vagrant/assets/selenium-test/src/SeleniumTest.html" \
# "/vagrant/assets/selenium-test/firefox-results.html"

# java -jar /vagrant/assets/selenium-server-standalone-2.45.0.jar \
# -htmlSuite *googlechrome http://www.google.com.com \
# "/vagrant/assets/selenium-test/src/SeleniumTest.html" \
# "/vagrant/assets/selenium-test/firefox-results.html"
