#!/bin/bash

WORKPATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
JAR="${WORKPATH}/selenium-server-standalone-2.45.0.jar"
FIREFOX="/Applications/Firefox.app/Contents/MacOS/firefox"
LOGFILE="${WORKPATH}/selenium-server.log"
PROFILE="${WORKPATH}/profile"

command -v java >/dev/null 2>&1 || { echo >&2 "I require java but it's not installed.  Aborting."; exit 1; }
command -v brew >/dev/null 2>&1 || { echo >&2 "I require brew but it's not installed.  Aborting."; exit 1; }
export PATH=/Applications/Firefox.app/Contents/MacOS/:${PATH}

BIN=`which java`
NAME="Selenium Server"
ARGS="-jar ${JAR} -firefoxProfileTemplate ${PROFILE} -trustAllSSLCertificates -log ${LOGFILE}"
PIDFILE="/tmp/selenium-server.pid"

case "$1" in
  init)
    echo "Initialing..."
    if [ ! -f ${JAR} ]; then
      wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
    fi
    if [ ! -d ${PROFILE} ]; then
      mkdir ${PROFILE}
      echo '{}' > ${PROFILE}/directoryLinks.json
      echo 'user_pref("extensions.checkCompatibility", false);' >> ${PROFILE}/prefs.js
      echo 'user_pref("browser.startup.page", 0);' >> ${PROFILE}/prefs.js
      echo '{"created":1375337719323,"reset":1430991977669}' > ${PROFILE}/times.json
    fi
    if [ "" == "`command -v chromedriver`" ]; then
      brew install chromedriver
    fi
    echo "Done"
    ;;
  start)
    echo -ne "Starting ${NAME}: "
    ${BIN} ${ARGS} &
    echo $! > ${PIDFILE}
    echo " ....OK"
    ;;
  stop)
    echo -ne "Stopping ${NAME}: "
    PID=`cat ${PIDFILE}`
    kill $PID
    rm -f $PIDFILE
    echo " ....OK"
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  *)
    echo "Usage: ${0} {start|stop|restart}"
    exit 1
esac

exit 0


# # For Test
# java -jar `pwd`/selenium-server-standalone-2.45.0.jar \
# -firefoxProfileTemplate "`pwd`/profile" \
# -htmlSuite "*firefox" http://www.google.com.tw \
# "`pwd`/SeleniumTest.html" \
# "`pwd`/results.html"
