#!/bin/bash

INPUT_FILE=${1-}

if [ "${INPUT_FILE}" = "" ]
then
  echo "No input file."
  exit 1
fi

OUTPUT_NAME=$(basename "$INPUT_FILE" .wiki)
pandoc -f mediawiki -t markdown -o "${OUTPUT_NAME}.md" "${INPUT_FILE}"